### ISSUE TITLE
Deploy this appliance in a Production server

### ISSUE THREAD

**Issue by apsbd** [cmu-sei/foundry-appliance#52]
Is this appliance is ready to deploy in a production env? Also, I'd like to know can I use Proxmox instead of vmware as hypervisor?

**Comment by sei-jbooz** [comment]
Hi apsbd, 

This appliance designed to be used as a standalone VM to run the foundry stack at the foundry.local domain. There are changes you will have to make to configurations in order to run these applications on a different domain, or in a production capacity. 

Using ProxMox rather than VMware as the hypervisor has been explored by our team, but has not yet been implemented. We will update our applications and this appliance as changes are made.
